# generate sample list of platforms
Platform.create({name: 'PC', slug: 'pc', external_id: '4', is_hidden: true})
Platform.create({name: 'PlayStation 5', slug: 'playstation5', external_id: '187', is_hidden: false})
Platform.create({name: 'Xbox One', slug: 'xbox-one', external_id: '1', is_hidden: false})
Platform.create({name: 'PlayStation 4', slug: 'playstation4', external_id: '18', is_hidden: false})
Platform.create({name: 'Xbox Series S/X', slug: 'xbox-series-x', external_id: '186', is_hidden: false})
Platform.create({name: 'Nintendo Switch', slug: 'nintendo-switch', external_id: '7', is_hidden: false})
Platform.create({name: 'iOS', slug: 'ios', external_id: '3', is_hidden: true})
Platform.create({name: 'Android', slug: 'android', external_id: '21', is_hidden: true})
Platform.create({name: 'Nintendo 3DS', slug: 'nintendo-3ds', external_id: '8', is_hidden: false})
Platform.create({name: 'Nintendo DS', slug: 'nintendo-ds', external_id: '9', is_hidden: false})
Platform.create({name: 'Nintendo DSi', slug: 'nintendo-dsi', external_id: '13', is_hidden: true})
Platform.create({name: 'macOS', slug: 'macos', external_id: '5', is_hidden: true})
Platform.create({name: 'Linux', slug: 'linux', external_id: '6', is_hidden: true})
Platform.create({name: 'Xbox 360', slug: 'xbox360', external_id: '14', is_hidden: false})
Platform.create({name: 'Xbox', slug: 'xbox-old', external_id: '80', is_hidden: false})
Platform.create({name: 'PlayStation 3', slug: 'playstation3', external_id: '16', is_hidden: false})
Platform.create({name: 'PlayStation 2', slug: 'playstation2', external_id: '15', is_hidden: false})
Platform.create({name: 'PlayStation', slug: 'playstation1', external_id: '27', is_hidden: false})
Platform.create({name: 'PS Vita', slug: 'ps-vita', external_id: '19', is_hidden: false})
Platform.create({name: 'PSP', slug: 'psp', external_id: '17', is_hidden: false})
Platform.create({name: 'Wii U', slug: 'wii-u', external_id: '10', is_hidden: false})
Platform.create({name: 'Wii', slug: 'wii', external_id: '11', is_hidden: false})
Platform.create({name: 'GameCube', slug: 'gamecube', external_id: '105', is_hidden: false})
Platform.create({name: 'Nintendo 64', slug: 'nintendo-64', external_id: '83', is_hidden: false})
Platform.create({name: 'Game Boy Advance', slug: 'game-boy-advance', external_id: '24', is_hidden: false})
Platform.create({name: 'Game Boy Color', slug: 'game-boy-color', external_id: '43', is_hidden: false})
Platform.create({name: 'Game Boy', slug: 'game-boy', external_id: '26', is_hidden: false})
Platform.create({name: 'SNES', slug: 'snes', external_id: '79', is_hidden: false})
Platform.create({name: 'NES', slug: 'nes', external_id: '49', is_hidden: false})
Platform.create({name: 'Classic Macintosh', slug: 'macintosh', external_id: '55', is_hidden: true})
Platform.create({name: 'Apple II', slug: 'apple-ii', external_id: '41', is_hidden: false})
Platform.create({name: 'Commodore / Amiga', slug: 'commodore-amiga', external_id: '166', is_hidden: false})
Platform.create({name: 'Atari 7800', slug: 'atari-7800', external_id: '28', is_hidden: false})
Platform.create({name: 'Atari 5200', slug: 'atari-5200', external_id: '31', is_hidden: false})
Platform.create({name: 'Atari 2600', slug: 'atari-2600', external_id: '23', is_hidden: false})
Platform.create({name: 'Atari Flashback', slug: 'atari-flashback', external_id: '22', is_hidden: false})
Platform.create({name: 'Atari 8-bit', slug: 'atari-8-bit', external_id: '25', is_hidden: false})
Platform.create({name: 'Atari ST', slug: 'atari-st', external_id: '34', is_hidden: false})
Platform.create({name: 'Atari Lynx', slug: 'atari-lynx', external_id: '46', is_hidden: false})
Platform.create({name: 'Atari XEGS', slug: 'atari-xegs', external_id: '50', is_hidden: false})
Platform.create({name: 'Genesis', slug: 'genesis', external_id: '167', is_hidden: false})
Platform.create({name: 'SEGA Saturn', slug: 'sega-saturn', external_id: '107', is_hidden: false})
Platform.create({name: 'SEGA CD', slug: 'sega-cd', external_id: '119', is_hidden: false})
Platform.create({name: 'SEGA 32X', slug: 'sega-32x', external_id: '117', is_hidden: false})
Platform.create({name: 'SEGA Master System', slug: 'sega-master-system', external_id: '74', is_hidden: false})
Platform.create({name: 'Dreamcast', slug: 'dreamcast', external_id: '106', is_hidden: false})
Platform.create({name: '3DO', slug: '3do', external_id: '111', is_hidden: false})
Platform.create({name: 'Jaguar', slug: 'jaguar', external_id: '112', is_hidden: false})
Platform.create({name: 'Game Gear', slug: 'game-gear', external_id: '77', is_hidden: false})
Platform.create({name: 'Neo Geo', slug: 'neogeo', external_id: '12', is_hidden: false})
Platform.create({name: 'Web', slug: 'web', external_id: '171', is_hidden: true})